[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/kayabaNerve/crypto-bigint?branch=c-repr"]
git = "https://github.com/kayabaNerve/crypto-bigint"
branch = "c-repr"
replace-with = "vendored-sources"

[source."git+https://github.com/monero-oxide/monero-oxide?rev=0e438aed2cce5c0ab8a935916c1a89bb0077f97f"]
git = "https://github.com/monero-oxide/monero-oxide"
rev = "0e438aed2cce5c0ab8a935916c1a89bb0077f97f"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/rust/vendor"
